---
#
# docker-compose up -d dev
#
services:
  dev:
    build:
      context: .
      target: dev
    working_dir: /code
    volumes:
    - .:/code

  api-catalog:
    build:
      context: apiv1
      dockerfile: catalog.dockerfile
    ports:
    - "8000:8080"
    volumes:
    - ./tests/api/vocabularies.linkset.yaml:/app/vocabularies.linkset.yaml:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/status"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
