name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - EricaCandido-86 
  pull_request:
    branches:
      - main

jobs:
  test-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Create dummy artifact
        run: |
          mkdir -p dist
          echo "This is a test artifact" > dist/schema_gov_it_tools.bin
          ls -l dist

      - name: Upload CLI binary artifact
        uses: actions/upload-artifact@v7
        with:
          name: cli-binary
          path: dist/schema_gov_it_tools.bin
          retention-days: 7